services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: ["sh", "-c", "echo OPENAI_API_KEY=$OPENAI_API_KEY && uvicorn main:app --host 0.0.0.0 --port 8000 --log-level debug"]