services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: ["npm", "run", "dev", "--", "--host"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env  # Ensure this path matches the actual location of .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - ./backend/.env  # Use the correct relative path to the .env file
