services:
  - type: web
    name: papi-chispa-frontend
    env: static
    rootDir: frontend
    buildCommand: pnpm install --no-frozen-lockfile && pnpm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://viteatsre-backend.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache

  - type: web
    name: papi-chispa-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --access-logfile - --error-logfile - --log-level info
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: CORS_ORIGINS
        value: https://viteatsre-frontend.onrender.com
    healthCheckPath: /
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    domains:
      - viteatsre-backend.onrender.com
